import uuid

from db.connection import get_db
from db.repositories import ArchetypeRepository
from services.drift_simulator import DriftSimulationConfig, DriftSimulator


def _create_agent(agent_id: str) -> None:
    with get_db() as conn:
        conn.execute(
            """
            INSERT OR REPLACE INTO agents (
                id, display_name, clawdbot_agent_id, vrm_model, voice_id, workspace,
                baseline_valence, baseline_arousal, baseline_dominance,
                emotional_volatility, emotional_recovery, emotional_profile
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                agent_id,
                "Test Agent",
                "test-claw-id",
                "emilia.vrm",
                None,
                None,
                0.2,
                0.0,
                0.0,
                0.5,
                0.1,
                "{}",
            ),
        )


def _create_archetype(archetype_id: str, message_triggers: list[list[list[str | float]]]) -> None:
    ArchetypeRepository.create(
        {
            "id": archetype_id,
            "name": "Test Archetype",
            "description": "Generated by tests",
            "message_triggers": message_triggers,
            "outcome_weights": {"positive": 0.4, "neutral": 0.4, "negative": 0.2},
            "sample_count": len(message_triggers),
            "source_filename": "tests",
        }
    )


def test_replay_sequential_cycles_trigger_sets():
    agent_id = f"agent-{uuid.uuid4().hex[:8]}"
    archetype_id = f"arch-{uuid.uuid4().hex[:8]}"
    _create_agent(agent_id)
    _create_archetype(
        archetype_id,
        [
            [["admiration", 0.91], ["approval", 0.62]],
            [["anger", 0.88]],
        ],
    )

    config = DriftSimulationConfig(
        agent_id=agent_id,
        user_id="sim-user",
        archetype=archetype_id,
        duration_days=1,
        sessions_per_day=1,
        messages_per_session=3,
        seed=7,
        replay_mode="sequential",
    )
    result = DriftSimulator(config).run()

    assert len(result.timeline) == 3
    assert result.timeline[0].trigger == "admiration"
    assert len(result.timeline[0].triggers) == 2
    assert result.timeline[1].trigger == "anger"
    assert result.timeline[2].trigger == "admiration"

    counts = {item.trigger: item.count for item in result.trigger_stats}
    assert counts["admiration"] == 2
    assert counts["approval"] == 2
    assert counts["anger"] == 1


def test_replay_random_uses_defined_trigger_pool():
    agent_id = f"agent-{uuid.uuid4().hex[:8]}"
    archetype_id = f"arch-{uuid.uuid4().hex[:8]}"
    _create_agent(agent_id)
    _create_archetype(
        archetype_id,
        [
            [["admiration", 0.8], ["approval", 0.55]],
            [["disappointment", 0.73]],
            [["amusement", 0.69], ["nervousness", 0.44]],
        ],
    )

    config = DriftSimulationConfig(
        agent_id=agent_id,
        user_id="sim-user",
        archetype=archetype_id,
        duration_days=1,
        sessions_per_day=1,
        messages_per_session=24,
        seed=42,
        replay_mode="random",
    )
    result = DriftSimulator(config).run()

    allowed = {"admiration", "approval", "disappointment", "amusement", "nervousness"}
    observed = {
        trigger_row["trigger"]
        for point in result.timeline
        for trigger_row in point.triggers
    }
    assert observed
    assert observed.issubset(allowed)
