/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelationshipsRouteImport } from './routes/relationships'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RelationshipsTypeRouteImport } from './routes/relationships.$type'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'

const RelationshipsRoute = RelationshipsRouteImport.update({
  id: '/relationships',
  path: '/relationships',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipsTypeRoute = RelationshipsTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => RelationshipsRoute,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/relationships': typeof RelationshipsRouteWithChildren
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/relationships/$type': typeof RelationshipsTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/relationships': typeof RelationshipsRouteWithChildren
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/relationships/$type': typeof RelationshipsTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/relationships': typeof RelationshipsRouteWithChildren
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/relationships/$type': typeof RelationshipsTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/relationships'
    | '/agents/$agentId'
    | '/relationships/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/relationships'
    | '/agents/$agentId'
    | '/relationships/$type'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/relationships'
    | '/agents/$agentId'
    | '/relationships/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  RelationshipsRoute: typeof RelationshipsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relationships': {
      id: '/relationships'
      path: '/relationships'
      fullPath: '/relationships'
      preLoaderRoute: typeof RelationshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationships/$type': {
      id: '/relationships/$type'
      path: '/$type'
      fullPath: '/relationships/$type'
      preLoaderRoute: typeof RelationshipsTypeRouteImport
      parentRoute: typeof RelationshipsRoute
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof AgentsRoute
    }
  }
}

interface AgentsRouteChildren {
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsAgentIdRoute: AgentsAgentIdRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface RelationshipsRouteChildren {
  RelationshipsTypeRoute: typeof RelationshipsTypeRoute
}

const RelationshipsRouteChildren: RelationshipsRouteChildren = {
  RelationshipsTypeRoute: RelationshipsTypeRoute,
}

const RelationshipsRouteWithChildren = RelationshipsRoute._addFileChildren(
  RelationshipsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  RelationshipsRoute: RelationshipsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
