export const DESIGNER_CONFIG = {
  CONFIDENCE_SAMPLE_THRESHOLD: 30,
  DIVERGENCE_THRESHOLD_SIMILAR: 0.15,
  DIVERGENCE_THRESHOLD_DIVERGING: 0.4,
  NUMERIC_EPSILON: 0.001,
  DEFAULT_DRIFT_DURATION_DAYS: 7,
  DEFAULT_SESSIONS_PER_DAY: 2,
  DEFAULT_MESSAGES_PER_SESSION: 20,
} as const;
