/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as DesignerV2RouteImport } from './routes/designer-v2'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserUserIdRouteImport } from './routes/user/$userId'
import { Route as UserUserIdIndexRouteImport } from './routes/user/$userId/index'
import { Route as UserUserIdChatNewRouteImport } from './routes/user/$userId/chat.new'
import { Route as UserUserIdChatSessionIdRouteImport } from './routes/user/$userId/chat.$sessionId'
import { Route as UserUserIdChatInitializingSessionIdRouteImport } from './routes/user/$userId/chat.initializing.$sessionId'
import { Route as UserUserIdRoomsRouteImport } from './routes/user/$userId/rooms'
import { Route as UserUserIdRoomsRoomIdRouteImport } from './routes/user/$userId/rooms.$roomId'

const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerV2Route = DesignerV2RouteImport.update({
  id: '/designer-v2',
  path: '/designer-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserIdRoute = UserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserIdIndexRoute = UserUserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserUserIdRoute,
} as any)
const UserUserIdChatNewRoute = UserUserIdChatNewRouteImport.update({
  id: '/chat/new',
  path: '/chat/new',
  getParentRoute: () => UserUserIdRoute,
} as any)
const UserUserIdChatSessionIdRoute = UserUserIdChatSessionIdRouteImport.update({
  id: '/chat/$sessionId',
  path: '/chat/$sessionId',
  getParentRoute: () => UserUserIdRoute,
} as any)
const UserUserIdChatInitializingSessionIdRoute =
  UserUserIdChatInitializingSessionIdRouteImport.update({
    id: '/chat/initializing/$sessionId',
    path: '/chat/initializing/$sessionId',
    getParentRoute: () => UserUserIdRoute,
  } as any)
const UserUserIdRoomsRoute = UserUserIdRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => UserUserIdRoute,
} as any)
const UserUserIdRoomsRoomIdRoute = UserUserIdRoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => UserUserIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/designer-v2': typeof DesignerV2Route
  '/manage': typeof ManageRoute
  '/user/$userId': typeof UserUserIdRouteWithChildren
  '/user/$userId/': typeof UserUserIdIndexRoute
  '/user/$userId/chat/$sessionId': typeof UserUserIdChatSessionIdRoute
  '/user/$userId/chat/new': typeof UserUserIdChatNewRoute
  '/user/$userId/chat/initializing/$sessionId': typeof UserUserIdChatInitializingSessionIdRoute
  '/user/$userId/rooms': typeof UserUserIdRoomsRoute
  '/user/$userId/rooms/$roomId': typeof UserUserIdRoomsRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/designer-v2': typeof DesignerV2Route
  '/manage': typeof ManageRoute
  '/user/$userId': typeof UserUserIdIndexRoute
  '/user/$userId/chat/$sessionId': typeof UserUserIdChatSessionIdRoute
  '/user/$userId/chat/new': typeof UserUserIdChatNewRoute
  '/user/$userId/chat/initializing/$sessionId': typeof UserUserIdChatInitializingSessionIdRoute
  '/user/$userId/rooms': typeof UserUserIdRoomsRoute
  '/user/$userId/rooms/$roomId': typeof UserUserIdRoomsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/designer-v2': typeof DesignerV2Route
  '/manage': typeof ManageRoute
  '/user/$userId': typeof UserUserIdRouteWithChildren
  '/user/$userId/': typeof UserUserIdIndexRoute
  '/user/$userId/chat/$sessionId': typeof UserUserIdChatSessionIdRoute
  '/user/$userId/chat/new': typeof UserUserIdChatNewRoute
  '/user/$userId/chat/initializing/$sessionId': typeof UserUserIdChatInitializingSessionIdRoute
  '/user/$userId/rooms': typeof UserUserIdRoomsRoute
  '/user/$userId/rooms/$roomId': typeof UserUserIdRoomsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug'
    | '/designer-v2'
    | '/manage'
    | '/user/$userId'
    | '/user/$userId/'
    | '/user/$userId/chat/$sessionId'
    | '/user/$userId/chat/new'
    | '/user/$userId/chat/initializing/$sessionId'
    | '/user/$userId/rooms'
    | '/user/$userId/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug'
    | '/designer-v2'
    | '/manage'
    | '/user/$userId'
    | '/user/$userId/chat/$sessionId'
    | '/user/$userId/chat/new'
    | '/user/$userId/chat/initializing/$sessionId'
    | '/user/$userId/rooms'
    | '/user/$userId/rooms/$roomId'
  id:
    | '__root__'
    | '/'
    | '/debug'
    | '/designer-v2'
    | '/manage'
    | '/user/$userId'
    | '/user/$userId/'
    | '/user/$userId/chat/$sessionId'
    | '/user/$userId/chat/new'
    | '/user/$userId/chat/initializing/$sessionId'
    | '/user/$userId/rooms'
    | '/user/$userId/rooms/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebugRoute: typeof DebugRoute
  DesignerV2Route: typeof DesignerV2Route
  ManageRoute: typeof ManageRoute
  UserUserIdRoute: typeof UserUserIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer-v2': {
      id: '/designer-v2'
      path: '/designer-v2'
      fullPath: '/designer-v2'
      preLoaderRoute: typeof DesignerV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$userId': {
      id: '/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof UserUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$userId/': {
      id: '/user/$userId/'
      path: '/'
      fullPath: '/user/$userId/'
      preLoaderRoute: typeof UserUserIdIndexRouteImport
      parentRoute: typeof UserUserIdRoute
    }
    '/user/$userId/chat/new': {
      id: '/user/$userId/chat/new'
      path: '/chat/new'
      fullPath: '/user/$userId/chat/new'
      preLoaderRoute: typeof UserUserIdChatNewRouteImport
      parentRoute: typeof UserUserIdRoute
    }
    '/user/$userId/chat/$sessionId': {
      id: '/user/$userId/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/user/$userId/chat/$sessionId'
      preLoaderRoute: typeof UserUserIdChatSessionIdRouteImport
      parentRoute: typeof UserUserIdRoute
    }
    '/user/$userId/chat/initializing/$sessionId': {
      id: '/user/$userId/chat/initializing/$sessionId'
      path: '/chat/initializing/$sessionId'
      fullPath: '/user/$userId/chat/initializing/$sessionId'
      preLoaderRoute: typeof UserUserIdChatInitializingSessionIdRouteImport
      parentRoute: typeof UserUserIdRoute
    }
    '/user/$userId/rooms': {
      id: '/user/$userId/rooms'
      path: '/rooms'
      fullPath: '/user/$userId/rooms'
      preLoaderRoute: typeof UserUserIdRoomsRouteImport
      parentRoute: typeof UserUserIdRoute
    }
    '/user/$userId/rooms/$roomId': {
      id: '/user/$userId/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/user/$userId/rooms/$roomId'
      preLoaderRoute: typeof UserUserIdRoomsRoomIdRouteImport
      parentRoute: typeof UserUserIdRoute
    }
  }
}

interface UserUserIdRouteChildren {
  UserUserIdIndexRoute: typeof UserUserIdIndexRoute
  UserUserIdChatSessionIdRoute: typeof UserUserIdChatSessionIdRoute
  UserUserIdChatNewRoute: typeof UserUserIdChatNewRoute
  UserUserIdChatInitializingSessionIdRoute: typeof UserUserIdChatInitializingSessionIdRoute
  UserUserIdRoomsRoute: typeof UserUserIdRoomsRoute
  UserUserIdRoomsRoomIdRoute: typeof UserUserIdRoomsRoomIdRoute
}

const UserUserIdRouteChildren: UserUserIdRouteChildren = {
  UserUserIdIndexRoute: UserUserIdIndexRoute,
  UserUserIdChatSessionIdRoute: UserUserIdChatSessionIdRoute,
  UserUserIdChatNewRoute: UserUserIdChatNewRoute,
  UserUserIdChatInitializingSessionIdRoute:
    UserUserIdChatInitializingSessionIdRoute,
  UserUserIdRoomsRoute: UserUserIdRoomsRoute,
  UserUserIdRoomsRoomIdRoute: UserUserIdRoomsRoomIdRoute,
}

const UserUserIdRouteWithChildren = UserUserIdRoute._addFileChildren(
  UserUserIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebugRoute: DebugRoute,
  DesignerV2Route: DesignerV2Route,
  ManageRoute: ManageRoute,
  UserUserIdRoute: UserUserIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
